application: flat-scraper
version: 1
runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: public
  secure: always

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- mail
